/* CREATE SCHEMA IF NOT EXISTS SALES; */
/* USE SALES; */

/*
CREATE TABLE SALES
(
PURCHASE_NUMBER INT NOT NULL PRIMARY KEY auto_increment,
DATE_OF_PURCHASE DATE NOT NULL , 
CUSTOMER_ID INT ,
ITEM_CODE VARCHAR(10) 

) ;
*/
/*
CREATE TABLE SALES
(
PURCHASE_NUMBER INT NOT NULL auto_increment,
DATE_OF_PURCHASE DATE NOT NULL , 
CUSTOMER_ID INT ,
ITEM_CODE VARCHAR(10) ,

PRIMARY KEY(PURCHASE_NUMBER) 

) ;
*/

/*
CREATE TABLE CUSTOMERS
(
CUSTOMER_ID INT PRIMARY KEY  ,
FIRST_NAME VARCHAR(255) ,
LAST_NAME VARCHAR(255) , 
EMAIL_ADDRESS VARCHAR(255) ,
NUM_OF_COMPLAINTS INT 
) ;
*/

/*
DROP TABLE SALES;
*/

-- CREATE TABLE ITEMS (
--     ITEM_CODE VARCHAR(255) PRIMARY KEY,
--     ITEM VARCHAR(255),
--     UNIT_PRICE NUMERIC(10 , 2 ),
--     COMPANY_ID VARCHAR(255)
-- );

-- CREATE TABLE COMPANIES (
--     COMPANY_ID VARCHAR(255) PRIMARY KEY,
--     COMPANY_NAME VARCHAR(255),
--     HQ_PHONE_NUMBER INT(12)
-- );






